import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ToasterContext from './context/ToasterContext';
import AuthContextProvider from './context/AuthContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title:"Nextjs-Drizzle",
  description: "Generated by Nextjs-Drizzle",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gradient-to-b from-[#0f0c29] via-[#302b63] to-[#24243e] relative z-[-2]">
        {/* <div className=" absolute left-0 top-[30%] w-full h-[10px] bg-[#e0dede] shadow-lg z-[-1]"></div>
        <div className=" absolute left-0 top-[40%] w-full h-[3px] bg-[#e0dede] shadow-md z-[-1]"></div> */}
      <AuthContextProvider>
          <ToasterContext />
          {children}
      </AuthContextProvider>
      </body>
    </html>
  );
}
